App\Entity\Club:
  attributes:
    id:
      groups: ['laliga']
    name:
      groups: ['laliga']
    budget:
      groups: ['laliga']
    coach:
      groups: ['laliga']
    players:
      groups: ['laliga']